const items = [
  {
    title: "Arduino",
    type: "Microcontroller Board",
    desc: "Electronic prototyping platform, easy to use, suitable for beginners",
    highlight: "Open-source software and hardware schematics, large community support, provides various software libraries",
    image_url: 'https://zh.wikipedia.org/wiki/File:Arduino_Uno_-_R3.jpg',
    video_url: 'https://www.youtube.com/watch?v=QxPBCBX8ac8',
  },
  {
    title: "Raspberry Pi",
    type: "Single Board Computer",
    desc: "Low-cost, compact computer for various applications, including education, prototyping, and media center",
    highlight: "More powerful than Arduino, can run full operating systems like Linux",
    image_url: 'https://www.raspberrypi.org/app/uploads/2021/01/RPi4-Model-B-Case-2-600x600.jpg',
    video_url: 'https://www.youtube.com/watch?v=7vhvnaWUZjE',
  },
  {
    title: "OpenROV",
    type: "Underwater Robot",
    desc: "Remotely operated underwater robot for exploration and research",
    highlight: "Open-source design, community collaboration, suitable for underwater exploration",
    image_url: 'https://openrov.com/wp-content/uploads/2013/05/rovs.jpg',
    video_url: 'https://www.youtube.com/watch?v=QxPBCBX8ac8',
  },
  {
    title: "RepRap",
    type: "3D Printer",
    desc: "Self-replicating machine that can replicate most of its parts",
    highlight: "Open-source design, allows users to build and modify their own 3D printers",
    image_url: 'https://reprap.org/mediawiki/images/1/15/RepRapPrusaI3.jpg',
    video_url: 'https://www.youtube.com/watch?v=RepRapPrinting',
  },
  {
    title: "Open Source Ecology",
    type: "Industrial Machinery",
    desc: "Open-source industrial machines for building small modern civilizations",
    highlight: "Global Village Construction Set (GVCS) with 50 types of industrial machines",
    image_url: 'https://opensourceecology.org/wp-content/uploads/2019/07/GC1.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenSourceEcology',
  },
  {
    title: "Precious Plastic",
    type: "Plastic Recycling Tools",
    desc: "Open-source tools for plastic recycling, including shredder, extruder, and injector",
    highlight: "Designed to make plastic recycling as simple as possible",
    image_url: 'https://preciousplastic.com/images/1.jpg',
    video_url: 'https://www.youtube.com/watch?v=PreciousPlastic',
  },
  {
    title: "WikiHouse",
    type: "Open Source Housing",
    desc: "Digitally designed open-source homes that can be manufactured locally",
    highlight: "Modular design, easy to assemble",
    image_url: 'https://wikihouse.cc/images/house.jpg',
    video_url: 'https://www.youtube.com/watch?v=WikiHouse',
  },
  {
    title: "OpenBCI",
    type: "Brain-Computer Interface",
    desc: "Open-source brain-computer interface platform for research and experimentation",
    highlight: "Can be used to control computers and other devices",
    image_url: 'https://openbci.com/wp-content/uploads/2018/07/openbci_ganglion.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenBCI',
  },
  {
    title: "FarmBot",
    type: "Automated Gardening Robot",
    desc: "Automated gardening robot for planting vegetables",
    highlight: "Open-source software and hardware, remotely controllable",
    image_url: 'https://farm.bot/images/farmbot.jpg',
    video_url: 'https://www.youtube.com/watch?v=FarmBot',
  },
  {
    title: "SafeCast",
    type: "Environmental Monitoring",
    desc: "Public domain environmental measurements",
    highlight: "Open-source hardware and data for monitoring radiation and other environmental hazards",
    image_url: 'https://safecast.org/wp-content/uploads/2020/04/safecast.jpg',
    video_url: 'https://www.youtube.com/watch?v=SafeCast',
  },
  {
    title: "ArduCopter",
    type: "Drone",
    desc: "Arduino-based drone platform",
    highlight: "Open-source hardware and software, customizable and extensible",
    image_url: 'https://ardusub.com/wp-content/uploads/2018/05/arducopter.jpg',
    video_url: 'https://www.youtube.com/watch?v=ArduCopter',
  },
  {
    title: "OpenMV",
    type: "Machine Vision Platform",
    desc: "Low-cost open-source machine vision platform",
    highlight: "Suitable for object detection, tracking, and recognition",
    image_url: 'https://openmv.io/images/openmv.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenMV',
  },
  {
    title: "Netduino",
    type: "Microcontroller Board",
    desc: "Microcontroller board based on .NET Micro Framework",
    highlight: "Programmable using C#",
    image_url: 'https://www.netduino.com/wp-content/uploads/2017/03/netduino.jpg',
    video_url: 'https://www.youtube.com/watch?v=Netduino',
  },
  {
    title: "NodeMCU",
    type: "Wi-Fi Microcontroller Board",
    desc: "Microcontroller board with Wi-Fi capability",
    highlight: "Easy to connect to Wi-Fi networks, suitable for IoT applications",
    image_url: 'https://nodemcu.readthedocs.io/en/latest/_images/nodemcu.jpg',
    video_url: 'https://www.youtube.com/watch?v=NodeMCU',
  },
  {
    title: "OpenFlexure Microscope",
    type: "Microscope",
    desc: "Open-source, 3D-printed microscope",
    highlight: "Includes precise mechanical platform",
    image_url: 'https://openflexure.org/images/microscope.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenFlexure',
  },
  {
    title: "Winterbloom",
    type: "Eurorack Module",
    desc: "Open-source Eurorack module",
    highlight: "Modular synthesizer components",
    image_url: 'https://winterbloom.com/images/winterbloom.jpg',
    video_url: 'https://www.youtube.com/watch?v=Winterbloom',
  },
  {
    title: "Open Gamma Detector",
    type: "Gamma Ray Spectrometer",
    desc: "Hacked, low-cost gamma ray spectrometer",
    highlight: "Used for measuring gamma radiation",
    image_url: 'https://opengammadevice.com/images/gamma_detector.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenGamma',
  },
  {
    title: "PiKVM",
    type: "IP-KVM",
    desc: "DIY IP-KVM based on Raspberry Pi",
    highlight: "Allows remote access and control of servers",
    image_url: 'https://pikvm.org/images/pikvm.jpg',
    video_url: 'https://www.youtube.com/watch?v=PiKVM',
  },
  {
    title: "Libre Computer Project",
    type: "Single Board Computer",
    desc: "Open-source, open-hardware single-board computer",
    highlight: "Various models available",
    image_url: 'https://libre.computer/images/libre_computer.jpg',
    video_url: 'https://www.youtube.com/watch?v=LibreComputer',
  },
  {
    title: "MNT Reform",
    type: "DIY Laptop",
    desc: "DIY laptop made with free software and open-source hardware",
    highlight: "Customizable and upgradable",
    image_url: 'https://mntreform.com/images/mnt_reform.jpg',
    video_url: 'https://www.youtube.com/watch?v=MNTReform',
  },
];