const items = [
  {
    title: "Arduino",
    type: "Microcontroller Board",
    desc: "Electronic prototyping platform, easy to use, suitable for beginners",
    highlight: "Open-source software and hardware schematics, large community support, provides various software libraries",
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Arduino_Uno_-_R3.jpg',
    video_url: 'https://www.youtube.com/watch?v=QxPBCBX8ac8',
  },
  {
    title: "Raspberry Pi",
    type: "Single Board Computer",
    desc: "Low-cost, compact computer for various applications, including education, prototyping, and media center",
    highlight: "More powerful than Arduino, can run full operating systems like Linux",
    image_url: 'https://electropeak.com/media/catalog/product/cache/a99a51fafac039a73087ecfaa8ccceba/m/i/min-01-117-1-raspberry-pi-4-board.jpg',
    video_url: 'https://www.youtube.com/watch?v=7vhvnaWUZjE',
  },
  {
    title: "OpenROV",
    type: "Underwater Robot",
    desc: "Remotely operated underwater robot for exploration and research",
    highlight: "Open-source design, community collaboration, suitable for underwater exploration",
    image_url: 'https://e4e.ucsd.edu/assets/openrov/openrov_big.jpg',
    video_url: 'https://www.youtube.com/watch?v=QxPBCBX8ac8',
  },
  {
    title: "RepRap",
    type: "3D Printer",
    desc: "Self-replicating machine that can replicate most of its parts",
    highlight: "Open-source design, allows users to build and modify their own 3D printers",
    image_url: 'https://reprap.org/mediawiki/images/thumb/c/c6/RepRapOneDarwin-darwin.jpg/600px-RepRapOneDarwin-darwin.jpg',
    video_url: 'https://www.youtube.com/watch?v=RepRapPrinting',
  },
  {
    title: "Open Source Ecology",
    type: "Industrial Machinery",
    desc: "Open-source industrial machines for building small modern civilizations",
    highlight: "Global Village Construction Set (GVCS) with 50 types of industrial machines",
    image_url: 'http://opensourceecology.org/wp-content/uploads/2015/05/OSE-microtrac-2015-infographic-907x624px1.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenSourceEcology',
  },
  {
    title: "Precious Plastic",
    type: "Plastic Recycling Tools",
    desc: "Open-source tools for plastic recycling, including shredder, extruder, and injector",
    highlight: "Designed to make plastic recycling as simple as possible",
    image_url: 'https://static.wixstatic.com/media/d73403_fb62652430364e6bae85334a21d98a11~mv2.jpg/v1/fill/w_1960,h_1102,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/d73403_fb62652430364e6bae85334a21d98a11~mv2.jpg',
    video_url: 'https://www.youtube.com/watch?v=PreciousPlastic',
  },
  {
    title: "WikiHouse",
    type: "Open Source Housing",
    desc: "Digitally designed open-source homes that can be manufactured locally",
    highlight: "Modular design, easy to assemble",
    image_url: 'https://cdn.archilovers.com/story/17980323bca045be80eda46284e6f987.jpg',
    video_url: 'https://www.youtube.com/watch?v=WikiHouse',
  },
  {
    title: "OpenBCI",
    type: "Brain-Computer Interface",
    desc: "Open-source brain-computer interface platform for research and experimentation",
    highlight: "Can be used to control computers and other devices",
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Openbci-brain-computer-interface-by-omphalosskeptic.png/500px-Openbci-brain-computer-interface-by-omphalosskeptic.png',
    video_url: 'https://www.youtube.com/watch?v=OpenBCI',
  },
  {
    title: "FarmBot",
    type: "Automated Gardening Robot",
    desc: "Automated gardening robot for planting vegetables",
    highlight: "Open-source software and hardware, remotely controllable",
    image_url: 'https://www.cloudamqp.com/img/blog/farmbot-rabbitmq.jpg',
    video_url: 'https://www.youtube.com/watch?v=FarmBot',
  },
  {
    title: "SafeCast",
    type: "Environmental Monitoring",
    desc: "Public domain environmental measurements",
    highlight: "Open-source hardware and data for monitoring radiation and other environmental hazards",
    image_url: 'https://orrery-media.s3.amazonaws.com/attr/2020-07/bGeigieyellow.jpg',
    video_url: 'https://www.youtube.com/watch?v=SafeCast',
  },
  {
    title: "ArduCopter",
    type: "Drone",
    desc: "Arduino-based drone platform",
    highlight: "Open-source hardware and software, customizable and extensible",
    image_url: 'https://s3-us-west-2.amazonaws.com/selbystorage/wp-content/uploads/2014/09/20130207/Slide1.jpg',
    video_url: 'https://www.youtube.com/watch?v=ArduCopter',
  },
  {
    title: "OpenMV",
    type: "Machine Vision Platform",
    desc: "Low-cost open-source machine vision platform",
    highlight: "Suitable for object detection, tracking, and recognition",
    image_url: 'https://m.media-amazon.com/images/I/516gYsNYujL._AC_SX679_.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenMV',
  },
  {
    title: "Netduino",
    type: "Microcontroller Board",
    desc: "Microcontroller board based on .NET Micro Framework",
    highlight: "Programmable using C#",
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/And_the_ARM_core.jpg/500px-And_the_ARM_core.jpg',
    video_url: 'https://www.youtube.com/watch?v=Netduino',
  },
  {
    title: "NodeMCU",
    type: "Wi-Fi Microcontroller Board",
    desc: "Microcontroller board with Wi-Fi capability",
    highlight: "Easy to connect to Wi-Fi networks, suitable for IoT applications",
    image_url: 'https://www.electronicwings.com/storage/PlatformSection/TopicContent/273/icon/NodeMCU%20GPIO.png',
    video_url: 'https://www.youtube.com/watch?v=NodeMCU',
  },
  {
    title: "OpenFlexure Microscope",
    type: "Microscope",
    desc: "Open-source, 3D-printed microscope",
    highlight: "Includes precise mechanical platform",
    image_url: 'https://openflexure.org/images/microscope.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenFlexure',
  },
  {
    title: "Winterbloom",
    type: "Eurorack Module",
    desc: "Open-source Eurorack module",
    highlight: "Modular synthesizer components",
    image_url: 'https://winterbloom.com/shop/castor-and-pollux/images/resized/cover-chonk.jpg',
    video_url: 'https://www.youtube.com/watch?v=Winterbloom',
  },
  {
    title: "Open Gamma Detector",
    type: "Gamma Ray Spectrometer",
    desc: "Hacked, low-cost gamma ray spectrometer",
    highlight: "Used for measuring gamma radiation",
    image_url: 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/05/rosspad_gamma-ray_detector/22009898-1-eng-GB/ROSSPAD_gamma-ray_detector_pillars.jpg',
    video_url: 'https://www.youtube.com/watch?v=OpenGamma',
  },
  {
    title: "PiKVM",
    type: "IP-KVM",
    desc: "DIY IP-KVM based on Raspberry Pi",
    highlight: "Allows remote access and control of servers",
    image_url: 'https://docs.pikvm.org/v4/overview.jpg',
    video_url: 'https://www.youtube.com/watch?v=PiKVM',
  },
  {
    title: "Libre Computer Project",
    type: "Single Board Computer",
    desc: "Open-source, open-hardware single-board computer",
    highlight: "Various models available",
    image_url: 'https://www.electromaker.io/uploads/images/Blog/Libre%20Computer%20Board/Ports.JPG',
    video_url: 'https://www.youtube.com/watch?v=LibreComputer',
  },
  {
    title: "MNT Reform",
    type: "DIY Laptop",
    desc: "DIY laptop made with free software and open-source hardware",
    highlight: "Customizable and upgradable",
    image_url: 'https://mntre.com/reform_next_images/nref-proto-overview.jpg',
    video_url: 'https://www.youtube.com/watch?v=MNTReform',
  },
];